apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ums
  name: ums
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ums
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ums
    spec:
      containers:
        - image: cst8277/ums-app:local
          name: ums-app
          resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ums
  name: ums
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: ums
  type: NodePort
status:
  loadBalancer: {}