spring:
    security:
        oauth2:
            client:
                registration:
                    github:
                        clientId: 208943b11d74efe07a98
                        clientSecret: 40f31d1f335b755e70388366a07b01da44c95bb6
